### ISSUE TITLE
提几个更上一层楼的建议

### ISSUE THREAD

**Issue by liyatang** [Aedron/Luoo.qy#1]
webpack.config.js 的写法是webpack1内的，1 和 2 是兼容的，不过还是建议切到新的写法

```
plugins: [
    //     new webpack.DefinePlugin({
    //         'process.env': {
    //             NODE_ENV: '"production"'
    //         }
    //     })
    // ],

// 可以这么写  JSON.stringify("production")
```

**Comment by elliothux** [comment]
😊 已经改了, Webpack3 都出了 😂 猝不及防, 得花时间研究一下了

**Comment by liyatang** [comment]
看了下autoUpdate代码， _installUpdate 是把zip包里的文件一个一个copy过去完事。 

如果文件目录或名字有更新，那么就存在新旧版本文件共存的情况，这样做是否有风险?

直接del以前文件夹，然后整个更新文件copy过去如何？

**Comment by elliothux** [comment]
确实会存在不同文件名的新旧文件共存的情况, 但是同时主进程和渲染进程文件也会一并更新, 更新之后并不会引用旧的不需要的文件;
为了尽量减少更新包的大小, 大多数时候只会更新某一个文件夹里的某一个文件, 
 直接删除文件夹会导致该文件夹里除了更新文件之外的所有文件被删除, 除非把文件夹里的其他所有文件也一并放入更新包, 但这样会造成不必要的更新包体积增大;
当然, 如果你愿意, 更改很少的代码就能实现替换整个文件夹的更新策略;
个人愚见, 大多数时候牺牲一点空间 (通常旧的文件都很小) 换取更新包的下载速度是值得的, 同时也能减小打包的复杂度和服务器的压力 😊

**Comment by testsla** [comment]
666，跪拜

**Comment by wuma2020** [comment]
能  加一个滚轴 吗？

**Comment by elliothux** [comment]
新的版本正在计划中，目前的版本只进行 BugFix。

**Comment by wuma2020** [comment]
了解。
