### ISSUE TITLE
Windows10 红石2 上点击注册按钮没有反应。

### ISSUE THREAD

**Issue by Hugo-Gao** [Aedron/Luoo.qy#2]

**Comment by elliothux** [comment]
抱歉, 你可以暂时到 http://www.luoo.net/ 进行注册, 谢谢你的反馈, 会尽快修复这个 Bug 😊

**Comment by Hugo-Gao** [comment]
能加入本地歌曲播放的功能吗，界面太好看，想同时当作本地歌曲播放器用

**Comment by elliothux** [comment]
😂 暂时没有这个计划, 但是以后可能会加入离线功能期刊和单曲功能
