### ISSUE TITLE
请问有考虑知识产权方面的问题吗？

### ISSUE THREAD

**Issue by DanielWLam** [Aedron/Luoo.qy#3]
本来以为是落网官方授权的，但是看了一下readme，登录注册，用户信息都不是正式渠道得到的东西，这样一个打着落网旗号的播放器，会不会有版权方面的问题？

**Comment by elliothux** [comment]
Luoo.qy 所有的数据都来自与 http://www.luoo.net/ 里的**公开的**内容, 并且**没有**对所有的内容作出任何修改, 也**没有**声明内容对于 Luoo.qy 的所有权, 也**没有**以任何商业目的使用这些内容, 相反地, 在下载和使用软件的过程中都**声明了内容的来源并且给出了官方链接**; 我开发 Luoo.qy 的初衷只是为了提升落网在电脑端的用户体验, 我相信这也是所有的第三方软件开发者的目的! 如果你介意, 建议你停止使用并卸载 Luoo.qy :)
