### ISSUE TITLE
请问一下linux(Ubuntu)上的安装方法

### ISSUE THREAD

**Issue by GuannanGuo** [Aedron/Luoo.qy#6]
如题，下载下来是一个zip文件，解压之后是一些文件，不知道如何安装。

**Comment by elliothux** [comment]
Linux 上是直接运行的, 无需安装, 输入 `./Luoo.qy` 即可

**Comment by GuannanGuo** [comment]
好像不行啊。
下载下来是一个名为"Luoo.qy-v1.0.zip"的压缩包，里面包含了"Luoo.qy-darwin-x64"和"__MACOSX"两个文件夹，两个文件夹里面都没有"Luoo.qy"这个文件。不解压直接运行压缩包也不行，说不是可执行的格式。

**Comment by elliothux** [comment]
用这个链接下载 http://os3s219a3.bkt.clouddn.com/Luoo.qy-linux-x64.zip, 解压后输入 ./Luoo.qy 运行。要是在 Ubuntu 上出现 error while loading shared libraries: libgconf-2.so.4 错误, 输入 apt-get install libgconf-2-4 再运行。

**Comment by GuannanGuo** [comment]
可以了，谢谢
