### ISSUE TITLE
音量调节问题（bug & 功能建议）

### ISSUE THREAD

**Issue by xaljer** [Aedron/Luoo.qy#7]
Bug：在调节音量时，用鼠标拖拽圆点，经常会出现拖至新位置后自行跳回原位置的现象。无论从底向高调节，还是从高向低调节。点击音量条某一位置来调节音量也会出现一样的问题，但似乎概率更小

建议：添加用鼠标滚轮调节音量的功能

---
OS: Windows10 1709
version: V1.2

**Comment by elliothux** [comment]
全新的v2.0版本正在计划中，这里会重新设计。
